services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noto_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '0000'
      POSTGRES_DB: noto
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - noto_postgres:/var/lib/postgresql/data

# volumes:
#   noto_postgres: